//EN
// Language
#define T_HEADER            "LUST Remote"
#define T_BLANK             ""
#define T_SCAN              "Scannning for LUST Wait..."
#define T_MENUE             "Menu"
#define T_DEMO              "Demo"
#define T_CONNECT           "Connect"
#define T_RESCAN            "Rescan"
#define T_SETTINGS          "Settings"
#define T_MOTD              "Welcome to LUST Remote"
#define T_BATT              "Batt"
#define T_CREAMPIE          "Creampie"
#define T_START             "Start/Stop"
#define T_CUM               "Cum"
#define T_HOME              "Home"
#define T_MEN1              "Up"
#define T_MEN2              "Down"
#define T_SPEED             "Speed:"
#define T_DEPTH             "Depth:"
#define T_MM                " mm"
#define T_STROKE            "Stroke:"
#define T_SENSATION         "Sensation:"
#define T_SETUP_DEPTH_I     "Set Depth Interactively"
#define T_SETUP_DEPTH_F     "Set Depth Fancy"
#define T_SELECT_PATTERN    "Select Pattern"
#define T_PATTERN_Button    "Select Pattern \n Menue"
#define T_RESTART           "Restart"
#define T_SETUP_TORQE       "Setup Torque"
#define T_OUT_TORQE         "Outward Torque:"
#define T_IN_TORQE          "Inward Torque:"
#define T_EJECT_SETTINGS    "EJECT Settings"
#define T_EJECT             "EJECT"
#define T_SAVE              "Save"
#define T_LOW               "Low"
#define T_HIGH              "High"
#define T_DARKM             "Dark Mode"
#define T_VIBRATE           "Vibrate"
#define T_TOUCHSETTING      "Touch Disabled"


#define T_Patterns          "Pattern:"
#define T_SimpleStroke      "Simple Stroke"
#define T_TeasingPounding   "Teasing or Pounding"
#define T_RoboStroke        "Robo Stroke"
#define T_HalfnHalf         "Half 'n' Half"
#define T_Deeper            "Deeper"
#define T_StopNGo           "Stop'n'Go"
#define T_Insist            "Insist"
#define T_JackHammer        "Jack Hammer"
#define T_StrokeNibbler     "Stroke Nibbler"

#define T_CUM_SPEED         "CUM Speed"
#define T_CUM_TIME          "CUM Time"
#define T_CUM_Volume        "CUM Volume"
#define T_CUM_Accel         "CUM Force"

#define T_FUCKS_MIN         " F/m"
